# Generated by Django 5.0 on 2026-02-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_isflagged_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
