# Generated by Django 5.0 on 2026-02-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_report_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Review',
            new_name='review',
        ),
    ]
